spring.application.name=dreamCommerce
#spring.config.import=classpath:env.properties
spring.config.import=optional:classpath:env.properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.jpa.hibernate.ddl-auto=update
api.cloudinary.key=${CLOUDINARY_API_KEY}
api.cloudinary.secret=${CLOUDINARY_API_SECRET}
api.cloudinary.name=${CLOUDINARY_CLOUD_NAME}
jwt.signing.key=${JWT_SIGNING_KEY}
#spring.profiles.active=test

spring.kafka.bootstrap-servers=localhost:9092

# Producer Configuration
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer Configuration
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#logging.level.org.apache.kafka=WARN
#logging.level.org.springframework.kafka=WARN